name: Release Please (Requirements)

on:
  push:
    branches:
      - main
      - release-please--branches--main**

jobs:
  release-please:
    uses: netwerk-digitaal-erfgoed/workflows/.github/workflows/release-please.yml@main
    with:
      working-directory: requirements
    secrets: inherit
