name: Publish Requirements

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'requirements/**'

defaults:
  run:
    working-directory: requirements

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npx --yes @lde/docgen@latest from-shacl shacl.ttl index.bs.liquid > index.bs

      - name: Build and validate
        uses: w3c/spec-prod@v2
        with:
          VALIDATE_MARKUP: false
          SOURCE: requirements/index.bs

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v6
        with:
          name: spec-prod-result-requirements
          path: requirements/

      - name: Deploy to docs.nde.nl
        uses: peaceiris/actions-gh-pages@v4
        with:
          external_repository: netwerk-digitaal-erfgoed/netwerk-digitaal-erfgoed.github.io
          personal_token: ${{ secrets.DATASET_REGISTER_PUBLISH_REQUIREMENTS }}
          publish_dir: requirements/
          publish_branch: main
          destination_dir: static/requirements-datasets/
          exclude_assets: '.github,.gitignore,index.bs,Makefile'
