name: Publish Requirements

on:
  push:
    branches:
      - main
    paths:
      - 'requirements/**'
  pull_request:
    branches:
      - main
    paths:
      - 'requirements/**'

defaults:
  run:
    working-directory: requirements

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npx --yes @lde/docgen@latest from-shacl -f shacl.frame.jsonld shacl.ttl index.bs.liquid > index.bs

      - name: Build and validate
        uses: w3c/spec-prod@v2
        with:
          VALIDATE_MARKUP: false
          SOURCE: requirements/index.bs

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: netwerk-digitaal-erfgoed
          repositories: netwerk-digitaal-erfgoed.github.io

      - uses: actions/checkout@v6
        with:
          repository: netwerk-digitaal-erfgoed/netwerk-digitaal-erfgoed.github.io
          token: ${{ steps.generate-token.outputs.token }}

      - uses: actions/download-artifact@v8
        with:
          name: spec-prod-result-requirements
          path: artifacts/

      - name: Copy build artifacts
        run: |
          rm -rf static/requirements-datasets/
          mkdir -p static/requirements-datasets/
          cp -r artifacts/* static/requirements-datasets/
          rm -f static/requirements-datasets/.gitignore static/requirements-datasets/index.bs static/requirements-datasets/Makefile
          rm -rf static/requirements-datasets/.github
        working-directory: .

      - name: Deploy to docs.nde.nl
        uses: grafana/github-api-commit-action@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: "deploy: ${{ github.repository }}@${{ github.sha }}"
          stage-all-files: true
          success-if-no-changes: true
