name: Validate requirements

on:
  pull_request:
    branches:
      - main
    paths:
      - 'requirements/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          VALIDATE_MARKUP: false
          SOURCE: requirements/index.bs
